### ISSUE TITLE
Cannot connect in state connected

### ISSUE THREAD

**Issue by shravankumarm** [SAP/node-hdb#112] opened 2017-12-20 16:13 UTC
Hi,
I'm using node-hdb to connect to my SAP HANA database.i have written couple of services in nodejs looking at node-hdb examples.i'm connecting and closing the connection to the database in all the services individually.

So when i'm accessing a service and its connection is established with the database in the mean time when i'm trying to access another service and it try's to connect to the database i get an error saying  

{ Error: Cannot connect in state "connected"
    at Immediate.deferError (C:\projects\DRT_Node\node_modules\hdb\lib\Client.js:162:19)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5) code: 'EHDBCONNECT' }.

So can you please let me know, how can i make multiple connections or the best practices to overcome the above error.

**Comment by alexpenev-s** [comment] 2017-12-21 08:54
Hi,
The error is likely to occur if you have an open connection and then you try to call connect on it again.
Make sure that the connection is closed before calling connect.

If you have an easy way to reproduce the issue paste the code here.

**Comment by shravankumarm** [comment] 2017-12-28 15:38
Thanks alex,
So it seems like i cannot call multiple services at once parallely.
Let's say i made a service request and its taking sometime to get response,in the mean while i will not be able to make another service request,technically i should close the 1st service connection and then make another service request.

service1
 function connect(cb) {
        client.connect(cb);
    }

function servcie1(cb){
//db actions which takes 1 min
}

function done(err, resp) {
    client.end();
     if (err) {
      return console.error(err);
      }
    res.send(resp);
}



service2
 function connect(cb) {
        client.connect(cb);
    }

function servcie2(cb){
//here i need to wait till the first service connection is closed ?
}

function done(err, resp) {
    client.end();
     if (err) {
      return console.error(err);
      }
    res.send(resp);
}

**Comment by alexpenev-s** [comment] 2017-12-29 08:56
Hi,
Yes you should be able to call multiple services simultaneously. There are different ways to go about it:
- Use connection pooling
- Open a separate connection for each service
- Share the same connection for all services - could you keep it open and not close and open it at the beginning of each request

**Comment by alexpenev-s** [comment] 2017-12-29 11:19
Closing not driver related.

**Closed by alexpenev-s** 2017-12-29 11:19 UTC

**Comment by shravankumarm** [comment] 2018-01-02 21:42
Hi,
node-hdb has any inbuilt connection-pooling features or we need to use npm packages like generic-pool or node-hdb-pool.

Can you please share any connection pooling examples.

**Comment by alexpenev-s** [comment] 2018-01-03 09:31
Hi,
I haven't tried the node-hdb-pool, but it looks like it will do the job. Alternatively you could use generic-pool to create your own.

**Comment by shravankumarm** [comment] 2018-01-30 17:31
Hi,
Can you please share me an example of using connection pooling (generic-pool) in services.

**Comment by alexpenev-s** [comment] 2018-01-31 09:49
Within SAP you can take a look at hdbext it implements connection pooling.
There is a new hana-client driver available at npm.sap.com in the future it should have connection pooling.

Additionally you could take a look at generic-pool and get familiar with examples on how to use it for resource management and plug in the hdb driver. 

Providing an example here is outside of the scope as it's complex.
